### PR TITLE
add events to monitor the requests for slow internet users

### PR DESCRIPTION
**Pull request by MajedDH**
when user have a slow internet connection now he can use fetch & update events to show some "loading" indicator.

PS: It is my first time to contribute on GitHub ... sorry if i made a mistake.. just mention it and i will make it right :) ..

### CODE REVIEW

**Comment by hootlex** [comment]
@MajedDH thanks for your contribution. :)

Though, you can make changes only within `src` and `test` directory (not `dist`).
Additionally, I think that if the paginator emits an event when it starts fetching it should also emit one when the request is complete.

**Comment by MajedDH** [comment]
I've added another two events to monitor the request.

**Comment by naneri** [comment]
Please merge this commit, as it is an important one, for being able to load indicators. Was thinking about the same.

**Comment by hootlex** [comment]
Merged! Thanks @MajedDH

**Pull request merged**
