### PR TITLE
Implements pagination with page numbers

### PR DESCRIPTION
**Pull request by israelss**
As requested by @caiquecastro on #11.

Also, included two more options: `previous_button_icon` and `next_button_icon`.

When using the pagination without `page_numbers` prop, the `[previous|next]_button_text` will have priority over `[previous|next]_button_icon`. When `page_numbers` is `true`, the icons have priority.
But in any case, the user still can override icon or text by passing a value on `options`.

The default icons are `glyphicon-chevron-left` and `glyphicon-chevron-right`.

I wrote some additional tests, but to be honest, until today I didn't have any experience with any kind of automatized tests, so if they are poorly written or if there are need for some more tests, please tell me!

### CODE REVIEW

**Comment by hootlex** [comment]
Great job @israelss 
Though, I think that the `page_number` property should be a key within `config`. Why did you choose this way?

previous_button_icon 👍

**Comment by israelss** [comment]
I think that it's simpler and easier to use it that way, but on a second thought I agree that it should be included within `config` and passed through `options`, specially because I plan to improve it, and include a `max_buttons` option, to include an ellipsis button when given too many pages, showing only `(max_buttons - 3)` + `ellipsis button` + `the two last buttons`, aside previous and next buttons.

E.g., with that `options`:

```
options: {
  page_numbers: true,
  max_buttons: 7
}
```
And with 13 pages in total, the result will be something like that (yes, i took that example from [Foundation 6 pagination](http://foundation.zurb.com/sites/docs/pagination.html)):

captura de tela de 2016-10-08 11 02 25

I will change it to be passed through `options` and fix a small bug that I just found out :sweat_smile:
The `max_buttons` feature will be implemented later, probably next week.

**Comment by israelss** [comment]
Ok, so ellipsis buttons are now available! :smiley:

A new option was created, `max_buttons`, and it defaults to `7`, i.e., when using `page_numbers: true` the default maximum number of page buttons will be 7, but using the `max_buttons` one can define any number to it (minimum recommended 5, minimum enforced 1). When passing a number lower than 1, the default value will be applied.

Another new option is `ellipses`, which defaults to `true`, and can be used to indicate if the paginator will use ellipsis buttons when the total of pages is greater than the `max_buttons` option.

What are your thoughts on these changes, @hootlex?

**Comment by nmfzone** [comment]
When will this be merged? I think it would be nice. Btw, is this support Vue 2?

**Comment by israelss** [comment]
@nmfzone it works fine with Vue 2 :+1:

**Comment by israelss** [comment]
One more addition, the `page_button_text` option. One can pass a string and it will be attached before the number of the page.

**Comment by hootlex** [comment]
Awesome work @israelss 
I will try to review and merge it today.

When it is done, do you plan on updating the [documentation](http://hootlex.github.io/vuejs-paginator/)?
If you don't, it's okay. I just want to know. :)

**Comment by hootlex** [comment]
@israelss

1. I am working on the plugin and I see that some times it generates 2 ellipses buttons.
What is the reason for this?
2. The page button prefix is cool!
3. Don't make any changes on this pr since I've already merged it and upated in a local branch.

**Comment by hootlex** [comment]
@israelss I think I'm done. Check [page-numbers branch](https://github.com/hootlex/vuejs-paginator/tree/page-numbers) and feel free to open a pr there if you want to make any changes.

**Comment by hootlex** [comment]
@israelss could I have an answer on 1?

**Comment by israelss** [comment]
Sorry, I was off the net the last two weeks.

Answering:
> When it is done, do you plan on updating the documentation?

I can work on the docs. But I can only start it on next week, is that ok?

> I am working on the plugin and I see that some times it generates 2 ellipses buttons. What is the reason for this?

Is that random/unexpected? When it is happening? :confused:

> The page button prefix is cool!

Thanks! :smiley:

> Check page-numbers branch and feel free to open a pr there if you want to make any changes.

I'll take a closer look tomorrow :+1:

**Comment by hootlex** [comment]
Hey @israelss, thanks for the quick update.

Regarding the ellipses, I dont think it is a bug since you are displaying them intentionally.
My question is, why? I've never seen a paginator with two ellipses.

**Comment by nmfzone** [comment]
Is there any update for this?

**Comment by gsuxlzt** [comment]
Hi. just wondering if this will be implemented? Thanks a lot.

**Comment by maqduni** [comment]
Yyyeah... is it happening? You guys don't seem to have been too active in the past 1.5 years :D. This is a good feature, so if anyone can finish the job it'd be awesome.

**Comment by hootlex** [comment]
https://github.com/hootlex/vuejs-paginator/issues/11

**Pull request closed without merging**
