### PR TITLE
Use HTTPS to load vue.js

### PR DESCRIPTION
**Pull request by danielsamuels**
HTTPS Everywhere was breaking your demo page, this PR fixes it.

### CODE REVIEW

**Comment by hootlex** [comment]
The demo page didn't work for you?

**Comment by danielsamuels** [comment]
No, hence the PR.

**Comment by ceejayoz** [comment]
@hootlex HTTPS Everywhere forces HTTPS where possible, and I can confirm in Chrome that the demos will fail at https://hootlex.github.io/vuejs-paginator/.

**Comment by hootlex** [comment]
That's weird since it works in any device I've checked. Anyway https everywhere is better :)

**Comment by hootlex** [comment]
@ceejayoz yeah you are right, I think I've never checked with https. Thanks guys!

**Pull request merged**
