### PR TITLE
fix https://github.com/hootlex/vuejs-paginator/issues/26

### PR DESCRIPTION
**Pull request by sebestenyb**

### CODE REVIEW

**Comment by hootlex** [comment]
Thanks for fixing the issue with the events, @sebestenyb.

Can you explain how is this [change](https://github.com/hootlex/vuejs-paginator/pull/27/commits/5b06f26c16016d1f73c944303a74b05a73ba3916) beneficial?

**Comment by sebestenyb** [comment]
Sure. 
The original code overwrote the request headers even if none was set on the component, in that case with an empty object.
This causes issues with for example authenticated APIs, where the Auth token is sent in the headers. As in Laravel and Vue.
Also can be an issue if the response type is determined by the content type request header.

So this changes is the the paginator should only overwrite the headers if they're explicitly defined on the component.

**Comment by hootlex** [comment]
Thanks for the explanation. Since the paginator handles the ajax requests by itself, it won't pass any headers unless they are specified in the `headers` property. 

Even if it was passing the headers, I don't see how theυ are not getting overwritten now, since `config` var is [initialized to an empty object](https://github.com/hootlex/vuejs-paginator/pull/27/commits/5b06f26c16016d1f73c944303a74b05a73ba3916#diff-35142a17e57d6f8bcaca0500775bd707R52).

**Comment by sebestenyb** [comment]
The config is an empty object, but if there's no headers key on it, axios
or vue-resource will use the default headers.

This change allows to keep the default headers if none is specified on the
component.

It's the common practice in Laravel that you define
axios.defaults.headers.common or Vue.headers.common in your app.js and it
will be used in every request - except it we overwrite it on instance
basis, which happens in the paginator without this snippet.

Cheers, Sebi

**Comment by hootlex** [comment]
Using `axios.defaults.headers` or `Vue.http.headers` is a good point.
Though, axios way won't work unless `Vue.http === axios`. This would be a nice improvement - fall back to axios if Vue.http is not defined.

Merged 🙂

**Pull request merged**
